version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: mm
      POSTGRES_PASSWORD: mm
      POSTGRES_DB: mm
    ports:
      - 5432:5432

  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/mm -schemas=mm -user=mm -password=mm -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db
    links:
      - db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
